package com.go.notification.processor.constants;

public enum JedisEnum {

	UNREADCOUNT, USERPRESENCE , RECENTCONVERSATIONINVITE , RECENTDMINVITE , LASTREADMESSAGEID , ACTIVECONVERSATION , NOTIFICATION ,
	TTL ,

}
